from __future__ import annotations

import hashlib
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = REPO_ROOT / "shared" / "openapi.json"
SWIFT_PATH = REPO_ROOT / "sweezy" / "sweezy" / "Core" / "Networking" / "Generated" / "OpenAPIClient.generated.swift"
TYPESCRIPT_PATH = REPO_ROOT / "admin" / "lib" / "generated" / "openapi.generated.ts"
HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def operations(spec: dict) -> list[dict]:
    result: list[dict] = []
    for path, path_item in sorted(spec.get("paths", {}).items()):
        for method, operation in sorted(path_item.items()):
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            security = operation.get("security") or []
            result.append(
                {
                    "id": operation.get("operationId") or f"{method}_{path}",
                    "method": method.upper(),
                    "path": path,
                    "authenticated": bool(security) and not any(item == {} for item in security),
                }
            )
    return result


def swift_source(items: list[dict], digest: str) -> str:
    rows = "\n".join(
        f'        "{item["id"]}": Operation(method: "{item["method"]}", path: "{item["path"]}", requiresAuthentication: {str(item["authenticated"]).lower()}),'
        for item in items
    )
    return f'''// Generated by backend/scripts/generate_clients.py. Do not edit.
import Foundation

enum GeneratedOpenAPIContract {{
    static let sha256 = "{digest}"

    struct Operation: Sendable {{
        let method: String
        let path: String
        let requiresAuthentication: Bool
    }}

    static let operations: [String: Operation] = [
{rows}
    ]
}}

struct GeneratedOpenAPIClient {{
    let baseURL: URL
    var session: URLSession = .shared

    func request<Response: Decodable>(
        _ operationID: String,
        pathParameters: [String: String] = [:],
        queryItems: [URLQueryItem] = [],
        body: Data? = nil,
        bearerToken: String? = nil,
        responseType: Response.Type
    ) async throws -> Response {{
        guard let operation = GeneratedOpenAPIContract.operations[operationID] else {{
            throw URLError(.unsupportedURL)
        }}
        var path = operation.path
        for (key, value) in pathParameters {{
            path = path.replacingOccurrences(of: "{{\\(key)}}", with: value.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? value)
        }}
        guard var components = URLComponents(url: baseURL.appendingPathComponent(path.trimmingCharacters(in: CharacterSet(charactersIn: "/"))), resolvingAgainstBaseURL: false) else {{
            throw URLError(.badURL)
        }}
        if !queryItems.isEmpty {{ components.queryItems = queryItems }}
        guard let url = components.url else {{ throw URLError(.badURL) }}
        var request = URLRequest(url: url)
        request.httpMethod = operation.method
        request.httpBody = body
        if body != nil {{ request.setValue("application/json", forHTTPHeaderField: "Content-Type") }}
        if let bearerToken, !bearerToken.isEmpty {{ request.setValue("Bearer \\(bearerToken)", forHTTPHeaderField: "Authorization") }}
        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode) else {{
            throw URLError(.badServerResponse)
        }}
        return try JSONDecoder().decode(Response.self, from: data)
    }}
}}
'''


def typescript_source(items: list[dict], digest: str) -> str:
    rows = "\n".join(
        f'  {json.dumps(item["id"])}: {{ method: {json.dumps(item["method"])}, path: {json.dumps(item["path"])}, requiresAuthentication: {str(item["authenticated"]).lower()} }},'
        for item in items
    )
    return f'''// Generated by backend/scripts/generate_clients.py. Do not edit.
export const openAPISha256 = {json.dumps(digest)}

export const operations = {{
{rows}
}} as const

export type OperationID = keyof typeof operations

export class GeneratedOpenAPIClient {{
  constructor(private readonly baseURL: string, private readonly getToken?: () => string | undefined) {{}}

  async request<Response>(operationID: OperationID, options: {{
    path?: Record<string, string>
    query?: Record<string, string | number | boolean | undefined>
    body?: unknown
  }} = {{}}): Promise<Response> {{
    const operation = operations[operationID]
    let path: string = operation.path
    for (const [key, value] of Object.entries(options.path ?? {{}})) {{
      path = path.replace(`{{${{key}}}}`, encodeURIComponent(value))
    }}
    const url = new URL(path, this.baseURL)
    for (const [key, value] of Object.entries(options.query ?? {{}})) {{
      if (value !== undefined) url.searchParams.set(key, String(value))
    }}
    const token = this.getToken?.()
    if (operation.requiresAuthentication && !token) throw new Error('Authentication required')
    const response = await fetch(url, {{
      method: operation.method,
      headers: {{
        ...(options.body === undefined ? {{}} : {{ 'Content-Type': 'application/json' }}),
        ...(token ? {{ Authorization: `Bearer ${{token}}` }} : {{}}),
      }},
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
      cache: 'no-store',
    }})
    if (!response.ok) throw new Error(`API ${{response.status}}: ${{await response.text()}}`)
    if (response.status === 204) return undefined as Response
    return await response.json() as Response
  }}
}}
'''


def run() -> None:
    raw = SPEC_PATH.read_bytes()
    spec = json.loads(raw)
    digest = hashlib.sha256(raw).hexdigest()
    items = operations(spec)
    SWIFT_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPESCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_PATH.write_text(swift_source(items, digest))
    TYPESCRIPT_PATH.write_text(typescript_source(items, digest))
    print(f"Generated {len(items)} operations for Swift and TypeScript")


if __name__ == "__main__":
    run()
